In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("Sample - Superstore.csv", encoding="latin1")

In [3]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [4]:
df.shape

(9994, 21)

In [5]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   object
 3   Ship Date      9994 non-null   object
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), object(15)
memory usage: 1.6+ MB

In [7]:
df.describe()

,Row ID,Postal Code,Sales,Quantity,Discount,Profit
count,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000
mean,4997.500000,55190.379428,229.858001,3.789574,0.156203,28.656896
std,2885.163629,32063.693350,623.245101,2.225110,0.206452,234.260108
min,1.000000,1040.000000,0.444000,1.000000,0.000000,-6599.978000
25%,2499.250000,23223.000000,17.280000,2.000000,0.000000,1.728750
50%,4997.500000,56430.500000,54.490000,3.000000,0.200000,8.666500
75%,7495.750000,90008.000000,209.940000,5.000000,0.200000,29.364000
max,9994.000000,99301.000000,22638.480000,14.000000,0.800000,8399.976000

In [8]:
df.isnull().sum()

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df.dtypes

Row ID             int64
Order ID          object
Order Date        object
Ship Date         object
Ship Mode         object
Customer ID       object
Customer Name     object
Segment           object
Country           object
City              object
State             object
Postal Code        int64
Region            object
Product ID        object
Category          object
Sub-Category      object
Product Name      object
Sales            float64
Quantity           int64
Discount         float64
Profit           float64
dtype: object

In [11]:
df['Order Date'] = pd.to_datetime(df['Order Date'])
df['Ship Date'] = pd.to_datetime(df['Ship Date'])

In [12]:
df.dtypes

Row ID                    int64
Order ID                 object
Order Date       datetime64[ns]
Ship Date        datetime64[ns]
Ship Mode                object
Customer ID              object
Customer Name            object
Segment                  object
Country                  object
City                     object
State                    object
Postal Code               int64
Region                   object
Product ID               object
Category                 object
Sub-Category             object
Product Name             object
Sales                   float64
Quantity                  int64
Discount                float64
Profit                  float64
dtype: object

In [13]:
df['Sales'].min()

0.444

In [14]:
df['Quantity'].min()

1

In [15]:
df['Discount'].unique()

array([0.  , 0.45, 0.2 , 0.8 , 0.3 , 0.5 , 0.7 , 0.6 , 0.32, 0.1 , 0.4 ,
       0.15])

In [16]:
df['Profit'].describe()

count    9994.000000
mean       28.656896
std       234.260108
min     -6599.978000
25%         1.728750
50%         8.666500
75%        29.364000
max      8399.976000
Name: Profit, dtype: float64

In [17]:
df[['Sales', 'Quantity', 'Discount', 'Profit']].describe()

              Sales     Quantity     Discount       Profit
count   9994.000000  9994.000000  9994.000000  9994.000000
mean     229.858001     3.789574     0.156203    28.656896
std      623.245101     2.225110     0.206452   234.260108
min        0.444000     1.000000     0.000000 -6599.978000
25%       17.280000     2.000000     0.000000     1.728750
50%       54.490000     3.000000     0.200000     8.666500
75%      209.940000     5.000000     0.200000    29.364000
max    22638.480000    14.000000     0.800000  8399.976000

In [18]:
len(df)

9994

In [19]:
total_sales = df['Sales'].sum()
total_profit = df['Profit'].sum()
total_orders = df['Order ID'].nunique()
total_customers = df['Customer ID'].nunique()
total_products = df['Product ID'].nunique()

In [20]:
df['Sales'].mean()

np.float64(229.85800083049827)

In [21]:
total_sales/total_orders

np.float64(458.6146656618087)

In [22]:
total_sales

np.float64(2297200.8603)

In [23]:
total_profit

np.float64(286397.0217)

In [24]:
profit_margin = (total_profit / total_sales) * 100
profit_margin

np.float64(12.467217240315605)

In [25]:
category_sales = df.groupby('Category')['Sales'].sum().sort_values(ascending=False)
category_sales

Category
Technology         836154.0330
Furniture          741999.7953
Office Supplies    719047.0320
Name: Sales, dtype: float64

In [26]:
category_profit = df.groupby('Category')['Profit'].sum().sort_values(ascending=False)
category_profit

Category
Technology         145454.9481
Office Supplies    122490.8008
Furniture           18451.2728
Name: Profit, dtype: float64

In [27]:
category_avg_discount = df.groupby('Category')['Discount'].mean().sort_values(ascending=False)
category_avg_discount

Category
Furniture          0.173923
Office Supplies    0.157285
Technology         0.132323
Name: Discount, dtype: float64

In [28]:
category_summary = df.groupby('Category').agg({'Sales': 'sum','Profit': 'sum'})

category_summary['Profit Margin (%)'] = (category_summary['Profit']/ category_summary['Sales']) * 100

category_summary.sort_values('Profit Margin (%)',ascending=False)

                       Sales       Profit  Profit Margin (%)
Category
Technology       836154.0330  145454.9481          17.395712
Office Supplies  719047.0320  122490.8008          17.035158
Furniture        741999.7953   18451.2728           2.486695

In [29]:
discount_profit = df.groupby('Discount')['Profit'].mean().sort_index()
discount_profit

Discount
0.00     66.900292
0.10     96.055074
0.15     27.288298
0.20     24.702572
0.30    -45.679636
0.32    -88.560656
0.40   -111.927429
0.45   -226.646464
0.50   -310.703456
0.60    -43.077212
0.70    -95.874060
0.80   -101.796797
Name: Profit, dtype: float64

In [30]:
region_sales = df.groupby('Region')['Sales'].sum().sort_values(ascending=False)
region_sales

Region
West       725457.8245
East       678781.2400
Central    501239.8908
South      391721.9050
Name: Sales, dtype: float64

In [31]:
region_profit = df.groupby('Region')['Profit'].sum().sort_values(ascending=False)
region_profit

Region
West       108418.4489
East        91522.7800
South       46749.4303
Central     39706.3625
Name: Profit, dtype: float64

In [32]:
region_summary = df.groupby('Region').agg({'Sales':'sum', 'Profit':'sum'})

region_summary['Profit Margin(%)'] = (region_summary['Profit'] / region_summary['Sales']) * 100

region_summary.sort_values('Profit Margin(%)', ascending=False)

               Sales       Profit  Profit Margin(%)
Region
West     725457.8245  108418.4489         14.944831
East     678781.2400   91522.7800         13.483399
South    391721.9050   46749.4303         11.934342
Central  501239.8908   39706.3625          7.921629

In [33]:
state_sales = df.groupby('State')['Sales'].sum().sort_values(ascending=False).head(10)
state_sales

State
California      457687.6315
New York        310876.2710
Texas           170188.0458
Washington      138641.2700
Pennsylvania    116511.9140
Florida          89473.7080
Illinois         80166.1010
Ohio             78258.1360
Michigan         76269.6140
Virginia         70636.7200
Name: Sales, dtype: float64

In [34]:
state_profit = df.groupby('State')['Profit'].sum().sort_values(ascending=False).head(10)
state_profit

State
California    76381.3871
New York      74038.5486
Washington    33402.6517
Michigan      24463.1876
Virginia      18597.9504
Indiana       18382.9363
Georgia       16250.0433
Kentucky      11199.6966
Minnesota     10823.1874
Delaware       9977.3748
Name: Profit, dtype: float64

In [35]:
state_summary = (df.groupby('State').agg({'Sales': 'sum','Profit': 'sum'}))

state_summary['Profit Margin (%)'] = (state_summary['Profit'] /state_summary['Sales']) * 100

state_summary.sort_values('Sales',ascending=False)

                            Sales      Profit  Profit Margin (%)
State
California            457687.6315  76381.3871          16.688541
New York              310876.2710  74038.5486          23.816082
Texas                 170188.0458 -25729.3563         -15.118192
Washington            138641.2700  33402.6517          24.092863
Pennsylvania          116511.9140 -15559.9603         -13.354823
Florida                89473.7080  -3399.3017          -3.799219
Illinois               80166.1010 -12607.8870         -15.727205
Ohio                   78258.1360 -16971.3766         -21.686405
Michigan               76269.6140  24463.1876          32.074618
Virginia               70636.7200  18597.9504          26.329012
North Carolina         55603.1640  -7490.9122         -13.472097
Indiana                53555.3600  18382.9363          34.325110
Georgia                49095.8400  16250.0433          33.098615
Kentucky               36591.7500  11199.6966          30.607163
New Jersey             35764.3120   9772.9138          27.325882
Arizona                35282.0010  -3427.9246          -9.715789
Wisconsin              32114.6100   8401.8004          26.161926
Colorado               32108.1180  -6527.8579         -20.330864
Tennessee              30661.8730  -5341.6936         -17.421289
Minnesota              29863.1500  10823.1874          36.242618
Massachusetts          28634.4340   6785.5016          23.696999
Delaware               27451.0690   9977.3748          36.346034
Maryland               23705.5230   7031.1788          29.660509
Rhode Island           22627.9560   7285.6293          32.197470
Missouri               22205.1500   6436.2105          28.985215
Oklahoma               19683.3900   4853.9560          24.660163
Alabama                19510.6400   5786.8253          29.659844
Oregon                 17431.1500  -1190.4705          -6.829558
Nevada                 16729.1020   3316.7659          19.826324
Connecticut            13384.3570   3511.4918          26.235790
Arkansas               11678.1300   4008.6871          34.326447
Utah                   11220.0560   2546.5335          22.696264
Mississippi            10771.3400   3172.9762          29.457581
Louisiana               9217.0300   2196.1023          23.826572
Vermont                 8929.3700   2244.9783          25.141508
South Carolina          8481.7100   1769.0566          20.857311
Nebraska                7464.9300   2037.0942          27.288859
New Hampshire           7292.5240   1706.5028          23.400716
Montana                 5589.3520   1833.3285          32.800377
New Mexico              4783.5220   1157.1161          24.189626
Iowa                    4579.7600   1183.8119          25.848776
Idaho                   4382.4860    826.7231          18.864250
Kansas                  2914.3100    836.4435          28.701253
District of Columbia    2865.0200   1059.5893          36.983662
Wyoming                 1603.1360    100.1960           6.250000
South Dakota            1315.5600    394.8283          30.012185
Maine                   1270.5300    454.4862          35.771387
West Virginia           1209.8240    185.9216          15.367657
North Dakota             919.9100    230.1497          25.018719

In [36]:
state_loss = df.groupby('State')['Profit'].sum().sort_values().head(10)
state_loss

State
Texas            -25729.3563
Ohio             -16971.3766
Pennsylvania     -15559.9603
Illinois         -12607.8870
North Carolina    -7490.9122
Colorado          -6527.8579
Tennessee         -5341.6936
Arizona           -3427.9246
Florida           -3399.3017
Oregon            -1190.4705
Name: Profit, dtype: float64

In [37]:
state_summary.sort_values('Profit Margin (%)').head(10)

                      Sales      Profit  Profit Margin (%)
State
Ohio             78258.1360 -16971.3766         -21.686405
Colorado         32108.1180  -6527.8579         -20.330864
Tennessee        30661.8730  -5341.6936         -17.421289
Illinois         80166.1010 -12607.8870         -15.727205
Texas           170188.0458 -25729.3563         -15.118192
North Carolina   55603.1640  -7490.9122         -13.472097
Pennsylvania    116511.9140 -15559.9603         -13.354823
Arizona          35282.0010  -3427.9246          -9.715789
Oregon           17431.1500  -1190.4705          -6.829558
Florida          89473.7080  -3399.3017          -3.799219

In [38]:
customer_sales = df.groupby('Customer ID')['Sales'].sum().sort_values(ascending=False).head(10)
customer_sales

Customer ID
SM-20320    25043.050
TC-20980    19052.218
RB-19360    15117.339
TA-21385    14595.620
AB-10105    14473.571
KL-16645    14175.229
SC-20095    14142.334
HL-15040    12873.298
SE-20110    12209.438
CC-12370    12129.072
Name: Sales, dtype: float64

In [39]:
customer_profit = df.groupby('Customer ID')['Profit'].sum().sort_values(ascending=False).head(10)
customer_profit

Customer ID
TC-20980    8981.3239
RB-19360    6976.0959
SC-20095    5757.4119
HL-15040    5622.4292
AB-10105    5444.8055
TA-21385    4703.7883
CM-12385    3899.8904
KD-16495    3038.6254
AR-10540    2884.6208
DR-12940    2869.0760
Name: Profit, dtype: float64

In [40]:
customers_generate_loss = df.groupby('Customer ID')['Profit'].sum().sort_values()

In [41]:
loss_customers = customers_generate_loss[customers_generate_loss < 0]
print(loss_customers.head(10))

Customer ID
CS-12505   -6626.3895
GT-14635   -4108.6589
LF-17185   -3583.9770
SR-20425   -3333.9144
HG-14965   -2797.9635
NC-18415   -2204.8072
SB-20290   -2082.7451
SM-20320   -1980.7393
CP-12340   -1850.3029
NF-18385   -1695.9714
Name: Profit, dtype: float64

In [42]:
customer_summary = df.groupby("Customer ID").agg(total_sales=("Sales", "sum"),total_profit=("Profit", "sum")).reset_index()

top_sales = customer_summary.sort_values("total_sales", ascending=False).head(10)
top_profit = customer_summary.sort_values("total_profit", ascending=False).head(10)

overlap = set(top_sales["Customer ID"]) & set(top_profit["Customer ID"])
print(f"\n{len(overlap)} of the top 10 sales customers are also top 10 profit customers:")
print(overlap)

6 of the top 10 sales customers are also top 10 profit customers:
{'TC-20980', 'AB-10105', 'SC-20095', 'TA-21385', 'RB-19360', 'HL-15040'}

In [43]:
customer_segment = df.groupby('Segment')['Profit'].sum().sort_values(ascending=False)
customer_segment

Segment
Consumer       134119.2092
Corporate       91979.1340
Home Office     60298.6785
Name: Profit, dtype: float64

In [44]:
product_sales = df.groupby('Sub-Category')['Sales'].sum().sort_values(ascending= False)
product_sales

Sub-Category
Phones         330007.0540
Chairs         328449.1030
Storage        223843.6080
Tables         206965.5320
Binders        203412.7330
Machines       189238.6310
Accessories    167380.3180
Copiers        149528.0300
Bookcases      114879.9963
Appliances     107532.1610
Furnishings     91705.1640
Paper           78479.2060
Supplies        46673.5380
Art             27118.7920
Envelopes       16476.4020
Labels          12486.3120
Fasteners        3024.2800
Name: Sales, dtype: float64

In [45]:
product_profit = df.groupby('Sub-Category')['Profit'].sum().sort_values(ascending= False)
product_profit

Sub-Category
Copiers        55617.8249
Phones         44515.7306
Accessories    41936.6357
Paper          34053.5693
Binders        30221.7633
Chairs         26590.1663
Storage        21278.8264
Appliances     18138.0054
Furnishings    13059.1436
Envelopes       6964.1767
Art             6527.7870
Labels          5546.2540
Machines        3384.7569
Fasteners        949.5182
Supplies       -1189.0995
Bookcases      -3472.5560
Tables        -17725.4811
Name: Profit, dtype: float64

In [46]:
product_loss = df.groupby('Sub-Category')['Profit'].sum().sort_values(ascending= True)
product_loss

Sub-Category
Tables        -17725.4811
Bookcases      -3472.5560
Supplies       -1189.0995
Fasteners        949.5182
Machines        3384.7569
Labels          5546.2540
Art             6527.7870
Envelopes       6964.1767
Furnishings    13059.1436
Appliances     18138.0054
Storage        21278.8264
Chairs         26590.1663
Binders        30221.7633
Paper          34053.5693
Accessories    41936.6357
Phones         44515.7306
Copiers        55617.8249
Name: Profit, dtype: float64

In [47]:
top_product_sales = df.groupby('Product Name')['Sales'].sum().sort_values(ascending= False).head(10)
top_product_sales

Product Name
Canon imageCLASS 2200 Advanced Copier                                          61599.824
Fellowes PB500 Electric Punch Plastic Comb Binding Machine with Manual Bind    27453.384
Cisco TelePresence System EX90 Videoconferencing Unit                          22638.480
HON 5400 Series Task Chairs for Big and Tall                                   21870.576
GBC DocuBind TL300 Electric Binding System                                     19823.479
GBC Ibimaster 500 Manual ProClick Binding System                               19024.500
Hewlett Packard LaserJet 3310 Copier                                           18839.686
HP Designjet T520 Inkjet Large Format Printer - 24" Color                      18374.895
GBC DocuBind P400 Electric Binding System                                      17965.068
High Speed Automatic Electric Letter Opener                                    17030.312
Name: Sales, dtype: float64

In [48]:
top_product_profit = df.groupby('Product Name')['Profit'].sum().sort_values(ascending= False).head(10)
top_product_profit

Product Name
Canon imageCLASS 2200 Advanced Copier                                          25199.9280
Fellowes PB500 Electric Punch Plastic Comb Binding Machine with Manual Bind     7753.0390
Hewlett Packard LaserJet 3310 Copier                                            6983.8836
Canon PC1060 Personal Laser Copier                                              4570.9347
HP Designjet T520 Inkjet Large Format Printer - 24" Color                       4094.9766
Ativa V4110MDD Micro-Cut Shredder                                               3772.9461
3D Systems Cube Printer, 2nd Generation, Magenta                                3717.9714
Plantronics Savi W720 Multi-Device Wireless Headset System                      3696.2820
Ibico EPK-21 Electric Binding System                                            3345.2823
Zebra ZM400 Thermal Label Printer                                               3343.5360
Name: Profit, dtype: float64

In [49]:
top_product_loss = df.groupby('Product Name')['Profit'].sum().sort_values().head(10)
top_product_loss

Product Name
Cubify CubeX 3D Printer Double Head Print                           -8879.9704
Lexmark MX611dhe Monochrome Laser Printer                           -4589.9730
Cubify CubeX 3D Printer Triple Head Print                           -3839.9904
Chromcraft Bull-Nose Wood Oval Conference Tables & Bases            -2876.1156
Bush Advantage Collection Racetrack Conference Table                -1934.3976
GBC DocuBind P400 Electric Binding System                           -1878.1662
Cisco TelePresence System EX90 Videoconferencing Unit               -1811.0784
Martin Yale Chadless Opener Electric Letter Opener                  -1299.1836
Balt Solid Wood Round Tables                                        -1201.0581
BoxOffice By Design Rectangular and Half-Moon Meeting Room Tables   -1148.4375
Name: Profit, dtype: float64

In [50]:
year_sales = df.groupby((df['Order Date'].dt.year))['Sales'].sum().sort_values(ascending=False)
year_sales

Order Date
2017    733215.2552
2016    609205.5980
2014    484247.4981
2015    470532.5090
Name: Sales, dtype: float64

In [51]:
month_sales = df.groupby((df['Order Date'].dt.month))['Sales'].sum().sort_values(ascending=False)
month_sales

Order Date
11    352461.0710
12    325293.5035
9     307649.9457
3     205005.4888
10    200322.9847
8     159044.0630
5     155028.8117
6     152718.6793
7     147238.0970
4     137762.1286
1      94924.8356
2      59751.2514
Name: Sales, dtype: float64

In [52]:
quarter_sales = df.groupby((df['Order Date'].dt.quarter))['Sales'].sum().sort_values(ascending=False)
quarter_sales

Order Date
4    878077.5592
3    613932.1057
2    445509.6196
1    359681.5758
Name: Sales, dtype: float64

In [53]:
year_profit = df.groupby((df['Order Date'].dt.year))['Profit'].sum().sort_values(ascending=False)
year_profit

Order Date
2017    93439.2696
2016    81795.1743
2015    61618.6037
2014    49543.9741
Name: Profit, dtype: float64

In [54]:
month_profit = df.groupby((df['Order Date'].dt.month))['Profit'].sum().sort_values(ascending=False)
month_profit

Order Date
12    43369.1919
9     36857.4753
11    35468.4265
10    31784.0413
3     28594.6872
5     22411.3078
8     21776.9384
6     21285.7954
7     13832.6648
4     11587.4363
2     10294.6107
1      9134.4461
Name: Profit, dtype: float64

In [55]:
quarter_profit = df.groupby((df['Order Date'].dt.quarter))['Profit'].sum().sort_values(ascending=False)
quarter_profit

Order Date
4    110621.6597
3     72467.0785
2     55284.5395
1     48023.7440
Name: Profit, dtype: float64

In [56]:
df.to_csv("Superstore_Analysis.csv", index=False, encoding="utf-8")

In [58]:
%pip install pymysql

Collecting pymysql
  Downloading pymysql-1.2.0-py3-none-any.whl.metadata (4.3 kB)
Downloading pymysql-1.2.0-py3-none-any.whl (45 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.2.0
Note: you may need to restart the kernel to use updated packages.

In [65]:
from sqlalchemy import create_engine
from urllib.parse import quote_plus

password = quote_plus("Jakkula@1964")

engine = create_engine(
    f"mysql+pymysql://root:{password}@localhost:3306/analysis"
)

In [66]:
with engine.connect() as conn:
    print("MySQL connection successful!")

MySQL connection successful!

In [67]:
df.to_sql(
    "superstore",
    con=engine,
    if_exists="replace",
    index=False
)

9994